#cert-manager-values.yml
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn:  "arn:aws:iam::022887457179:role/cert-manager-r53"

installCRDs: true

# the securityContext is required, so the pod can access files required to assume the IAM role
securityContext:
  enabled: true
  fsGroup: 1001