loki:
  isDefault: false
  namespace: monitoring
  url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
  config:
    table_manager:
      retention_period: 168h
  persistence:
    enabled: true
    storageClassName: gp3
    accessModes:
    - ReadWriteOnce
    size: 20Gi  
    
promtail:
  clients:
    -   url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}/loki/api/v1/push
