apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificado-tls
  namespace: cert-manager
spec:
  secretName: certificado-tls
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: ""
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "guilhermefreis.com"
  - "*.guilhermefreis.com"
