global:
  prometheus:
    fqdn: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
    enabled: false
  grafana:
    enabled: false

prometheus:
  nodeExporter:
    enabled: false
  kube-state-metrics:
    disabled: true
  serviceAccounts:
    nodeExporter:
      create: false