{
 "title": "Dash Teste",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests Last 24hrs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total{job=\"servico-principal\"}[24h])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Avarage Duration Last 5m",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{job=\"servico-principal\"}[5m])) by (path, method, status) /\nsum(rate(flask_http_request_duration_seconds_count{job=\"servico-principal\"}[5m])) by (path, method, status)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests by Route last 5m",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_duration_seconds_count{job=\"servico-principal\"}[5m])) by (method, path)\n",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests by Route last 30m",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_duration_seconds_count{job=\"servico-principal\"}[30m])) by (method, path)\n",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"servico-principal\", namespace=\"default\"} !~ \"/metrics\""
    }
   ]
  }
 ]
}